name: backend executing
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
          echo "Build Web App"
          sleep 10s 
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: jayanth9652
          repo: demo-frontend
          github_token: ${{ secrets.MY_PAT_BACK }}
          workflow_file_name: demo-frontend.yml
          ref: dev
